# -*- coding: utf-8 -*-
"""HW9_Week10_Md Shadman Shakib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjM53XSr6hbOrJOiQZ15m4iLoKSvDBJS
"""

from google.colab import drive
drive.mount('/content/drive')

!uv pip install ultralytics
import ultralytics  # https://www.ultralytics.com/
ultralytics.checks()

from ultralytics import YOLO

# Load a pretrained YOLO model
model = YOLO("yolo11n.pt")

# Perform object detection on an image
results = model("https://ultralytics.com/images/bus.jpg")

# Visualize the results
for result in results:
    result.show()

from ultralytics import YOLO
import pandas as pd
import matplotlib.pyplot as plt
import os

# Set path to your dataset (data.yaml)
data_path = '/content/drive/MyDrive/AGST 892/Week10/coccinellids-1.v2i.yolov9/data.yaml'

# Model and experiment settings
model = YOLO("yolo11n.pt")
num_epochs = 300
img_size = 416
batch_size = 16
learing_rate = 0.001
exp_name = 'custom_train'
project_path = '/content/drive/MyDrive/AGST 892/Week10/coccinellids-1.v2i.yolov9/output'

# ✅ Train for 50 epochs with validation after each epoch
model.train(
    data=data_path,
    epochs=num_epochs,
    imgsz=img_size,
    batch=batch_size,
    lr0=learing_rate,
    name=exp_name,
    project=project_path,
    patience = 50
)

# ✅ OPTIONAL: Evaluate on test set after training
metrics = model.val(
    data=data_path,
    split='test'  # or 'val' if you want validation metrics instead
)
print("📊 Test set metrics:", metrics.results_dict)

# ✅ Plot training + validation curves from results.csv
results_csv_path = os.path.join("/content/drive/MyDrive/AGST 892/Week10/coccinellids-1.v2i.yolov9/output/custom_train/results.csv")
df = pd.read_csv(results_csv_path)
df.head()

# Clean up column names (some may have leading/trailing spaces)
df.columns = df.columns.str.strip()

# 📈 Plot training losses
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['val/box_loss'], label='Box Loss')
plt.plot(df['epoch'], df['val/cls_loss'], label='Class Loss')
plt.plot(df['epoch'], df['val/dfl_loss'], label='DFL Loss')
plt.title("Training Losses Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# 📈 Plot validation metrics
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['metrics/precision(B)'], label='Precision')
plt.plot(df['epoch'], df['metrics/recall(B)'], label='Recall')
plt.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@50')
plt.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@50-95')
plt.title("Validation Metrics Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Metric Value")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import os
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np
# Load the trained model (e.g., best.pt or last.pt)
model = YOLO('/content/drive/MyDrive/AGST 892/Week10/coccinellids-1.v2i.yolov9/output/custom_train/weights/best.pt')

image_dir = '/content/drive/MyDrive/AGST 892/Week10/coccinellids-1.v2i.yolov9/test/images'   # Your test image folder
label_dir = '/content/drive/MyDrive/AGST 892/Week10/coccinellids-1.v2i.yolov9/test/labels'   # Corresponding label folder

# Run predictions on test images
results = model.predict(
    source='//content/drive/MyDrive/AGST 892/Week10/coccinellids-1.v2i.yolov9/test/images',  # Update path
    conf=0.5,
    imgsz=416,
    save=True,  # saves images to 'runs/detect/predict'
    show=False
)

# Class names from the model
class_names = model.names

# Load image paths
image_files = sorted([
    os.path.join(image_dir, f)
    for f in os.listdir(image_dir)
    if f.lower().endswith(('.jpg', '.png'))
])[:10]  # Limit to first 10

# Plot settings
fig, axes = plt.subplots(2, 5, figsize=(40, 16))

for i, ax in enumerate(axes.flat):
    if i >= len(image_files):
        ax.axis('off')
        continue

    # Load image
    img_path = image_files[i]
    image = Image.open(img_path).convert("RGB")
    img_width, img_height = image.size

    # Draw image
    ax.imshow(image)
    ax.set_title(f"Image {i+1}")
    ax.axis('off')

    # ========== Draw Ground Truth Boxes ==========
    label_path = os.path.join(label_dir, os.path.splitext(os.path.basename(img_path))[0] + '.txt')
    if os.path.exists(label_path):
        with open(label_path, 'r') as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                # Convert YOLO to pixel coords
                x1 = (x - w/2) * img_width
                y1 = (y - h/2) * img_height
                box_w = w * img_width
                box_h = h * img_height
                rect = patches.Rectangle((x1, y1), box_w, box_h,
                                         linewidth=2, edgecolor='lime', facecolor='none')
                ax.add_patch(rect)
                ax.text(x1, y1 - 4, f"GT: {class_names[int(cls)]}", color='lime', fontsize=10, weight='bold')

    # ========== Draw Predicted Boxes ==========
    pred_result = results[i]
    for box in pred_result.boxes:
        cls_id = int(box.cls[0])
        conf = float(box.conf[0])
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1,
                                 linewidth=2, edgecolor='red', facecolor='none')
        ax.add_patch(rect)
        ax.text(x1, y1 - 4, f"{conf:.2f}",
                color='red', fontsize=16, weight='bold')

plt.tight_layout()
plt.show()



"""## 📊 Comparison: Roboflow vs YOLO in Colab

| Feature                     | ✅ Roboflow (Cloud)                | 💻 YOLO in Colab (Manual)          |
|----------------------------|------------------------------------|------------------------------------|
| Ease of Use                | ✅ Very easy (UI-based)             | 🧠 Requires Python knowledge        |
| Model Architecture Control | ❌ Fixed (YOLOv5/v7)                | ✅ Full control (YOLOv5, YOLOv8, etc.) |
| Hyperparameter Tuning      | ❌ Limited                          | ✅ Fully customizable               |
| Augmentation Settings      | ❌ Predefined, limited              | ✅ Fully customizable (Albumentations, etc.) |
| Validation per Epoch       | ✅ Yes                              | ✅ Yes                              |
| Visual Debugging           | ❌ Minimal                          | ✅ Full access (loss curves, metrics, etc.) |
| GPU Speed / Resources      | 🐢 Shared cloud (can be slow)       | ⚡ Faster (Colab GPU, local GPU)    |
| Callbacks / Early Stop     | ❌ Not available                    | ✅ Fully supported                  |
| Deployment Options         | ✅ Hosted APIs (easy)               | ✅ ONNX, TorchScript, TFLite, etc.  |
| Best For                   | 🔰 Beginners, quick experiments     | 🧪 Research, education, fine-tuning |

"""



"""#**Homework 9**
We will work on the Ripe Strawberries Object Detection Dataset in this homework. 40 digital images of greenhouse grown strawberries are provided in the shared Google Drive folder. You can also find more details about the dataset here: https://www.kaggle.com/datasets/trainingdatapro/ripe-strawberries-detection

<font color='green'>**Goal:**
- Implementing object detection using a same YOLO varient in both roboflow and Colab to detect ripe strawberries in images.
(Optional: You can also detect unripe strawberries as an additional class of object.)
- Compare the performance of the two approaches, i.e., roboflow and Colab implementations.
- Compare two different data pre-processing and/or data augmentation configurations/settings.

<font color='green'>**Note:**

Label the 40 images in roboflow will take you about 40 to 60 minutes.

<font color='green'>**Submission:**

Write a report (in PDF) including
- A beginning paragrph / brief summary of what you did.
- Key model performance metrics, i.e., mAP@50, mAP@50:95, precision, recall of test set of both approaches.
- Advanced Training Graphs in roboflow and the graph of loss curve in Colab. Make sure they are in appropriate sizes that texts in the graphs are readible.
- Show the model prediction results of a few test images from both approaches.
- A discussion and conclusion paragraph.






"""

from ultralytics import YOLO
import pandas as pd
import matplotlib.pyplot as plt
import os

# Set path to your dataset (data.yaml)
data_path = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/data.yaml'

# Model and experiment settings
model = YOLO("yolo11n.pt")
num_epochs = 300
img_size = 640
batch_size = 16
learing_rate = 0.001
exp_name = 'custom_train'
project_path = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/output'

# ✅ Train for 50 epochs with validation after each epoch
model.train(
    data=data_path,
    epochs=num_epochs,
    imgsz=img_size,
    batch=batch_size,
    lr0=learing_rate,
    name=exp_name,
    project=project_path,
    patience = 50
)

# ✅ OPTIONAL: Evaluate on test set after training
metrics = model.val(
    data=data_path,
    split='test'  # or 'val' if you want validation metrics instead
)
print("📊 Test set metrics:", metrics.results_dict)

results_csv_path = os.path.join("/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/output/custom_train/results.csv")
df = pd.read_csv(results_csv_path)
df.head()

# Clean up column names (some may have leading/trailing spaces)
df.columns = df.columns.str.strip()

# 📈 Plot training losses
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['val/box_loss'], label='Box Loss')
plt.plot(df['epoch'], df['val/cls_loss'], label='Class Loss')
plt.plot(df['epoch'], df['val/dfl_loss'], label='DFL Loss')
plt.title("Training Losses Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# 📈 Plot validation metrics
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['metrics/precision(B)'], label='Precision')
plt.plot(df['epoch'], df['metrics/recall(B)'], label='Recall')
plt.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@50')
plt.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@50-95')
plt.title("Validation Metrics Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Metric Value")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import os
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np
# Load the trained model (e.g., best.pt or last.pt)
model = YOLO('/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/output/custom_train/weights/best.pt')

image_dir = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/test/images'   # Your test image folder
label_dir = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/test/labels'   # Corresponding label folder

# Run predictions on test images
results = model.predict(
    source='/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/test/images',  # Update path
    conf=0.5,
    imgsz=640,
    save=True,  # saves images to 'runs/detect/predict'
    show=False
)

# Class names from the model
class_names = model.names

# Load image paths
image_files = sorted([
    os.path.join(image_dir, f)
    for f in os.listdir(image_dir)
    if f.lower().endswith(('.jpg', '.png'))
])[:10]  # Limit to first 10

# Plot settings
fig, axes = plt.subplots(2, 5, figsize=(40, 16))

for i, ax in enumerate(axes.flat):
    if i >= len(image_files):
        ax.axis('off')
        continue

    # Load image
    img_path = image_files[i]
    image = Image.open(img_path).convert("RGB")
    img_width, img_height = image.size

    # Draw image
    ax.imshow(image)
    ax.set_title(f"Image {i+1}")
    ax.axis('off')

    # ========== Draw Ground Truth Boxes ==========
    label_path = os.path.join(label_dir, os.path.splitext(os.path.basename(img_path))[0] + '.txt')
    if os.path.exists(label_path):
        with open(label_path, 'r') as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                # Convert YOLO to pixel coords
                x1 = (x - w/2) * img_width
                y1 = (y - h/2) * img_height
                box_w = w * img_width
                box_h = h * img_height
                rect = patches.Rectangle((x1, y1), box_w, box_h,
                                         linewidth=2, edgecolor='lime', facecolor='none')
                ax.add_patch(rect)
                ax.text(x1, y1 - 4, f"GT: {class_names[int(cls)]}", color='lime', fontsize=10, weight='bold')

    # ========== Draw Predicted Boxes ==========
    pred_result = results[i]
    for box in pred_result.boxes:
        cls_id = int(box.cls[0])
        conf = float(box.conf[0])
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1,
                                 linewidth=2, edgecolor='red', facecolor='none')
        ax.add_patch(rect)
        ax.text(x1, y1 - 4, f"{conf:.2f}",
                color='red', fontsize=16, weight='bold')

plt.tight_layout()
plt.show()

from ultralytics import YOLO
import pandas as pd
import matplotlib.pyplot as plt
import os

# Set path to your dataset (data.yaml)
data_path = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/data.yaml'

# Model and experiment settings
model = YOLO("yolo11x.pt")
num_epochs = 300
img_size = 640
batch_size = 16
learing_rate = 0.001
exp_name = 'custom_train'
project_path = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/output_yolo11x'

# ✅ Train for 50 epochs with validation after each epoch
model.train(
    data=data_path,
    epochs=num_epochs,
    imgsz=img_size,
    batch=batch_size,
    lr0=learing_rate,
    name=exp_name,
    project=project_path,
    patience = 50
)

# ✅ OPTIONAL: Evaluate on test set after training
metrics = model.val(
    data=data_path,
    split='test'  # or 'val' if you want validation metrics instead
)
print("📊 Test set metrics:", metrics.results_dict)

results_csv_path = os.path.join("/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/output_yolo11x/custom_train/results.csv")
df = pd.read_csv(results_csv_path)
df.head()

# Clean up column names (some may have leading/trailing spaces)
df.columns = df.columns.str.strip()

# 📈 Plot training losses
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['val/box_loss'], label='Box Loss')
plt.plot(df['epoch'], df['val/cls_loss'], label='Class Loss')
plt.plot(df['epoch'], df['val/dfl_loss'], label='DFL Loss')
plt.title("Training Losses Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# 📈 Plot validation metrics
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['metrics/precision(B)'], label='Precision')
plt.plot(df['epoch'], df['metrics/recall(B)'], label='Recall')
plt.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@50')
plt.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@50-95')
plt.title("Validation Metrics Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Metric Value")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import os
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np
# Load the trained model (e.g., best.pt or last.pt)
model = YOLO('/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/output_yolo11x/custom_train/weights/best.pt')

image_dir = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/test/images'   # Your test image folder
label_dir = '/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/test/labels'   # Corresponding label folder

# Run predictions on test images
results = model.predict(
    source='/content/drive/MyDrive/AGST 892/Week10/Strawberry.v3i.yolov11/test/images',  # Update path
    conf=0.5,
    imgsz=640,
    save=True,  # saves images to 'runs/detect/predict'
    show=False
)

# Class names from the model
class_names = model.names

# Load image paths
image_files = sorted([
    os.path.join(image_dir, f)
    for f in os.listdir(image_dir)
    if f.lower().endswith(('.jpg', '.png'))
])[:10]  # Limit to first 10

# Plot settings
fig, axes = plt.subplots(2, 5, figsize=(40, 16))

for i, ax in enumerate(axes.flat):
    if i >= len(image_files):
        ax.axis('off')
        continue

    # Load image
    img_path = image_files[i]
    image = Image.open(img_path).convert("RGB")
    img_width, img_height = image.size

    # Draw image
    ax.imshow(image)
    ax.set_title(f"Image {i+1}")
    ax.axis('off')

    # ========== Draw Ground Truth Boxes ==========
    label_path = os.path.join(label_dir, os.path.splitext(os.path.basename(img_path))[0] + '.txt')
    if os.path.exists(label_path):
        with open(label_path, 'r') as f:
            for line in f:
                cls, x, y, w, h = map(float, line.strip().split())
                # Convert YOLO to pixel coords
                x1 = (x - w/2) * img_width
                y1 = (y - h/2) * img_height
                box_w = w * img_width
                box_h = h * img_height
                rect = patches.Rectangle((x1, y1), box_w, box_h,
                                         linewidth=2, edgecolor='lime', facecolor='none')
                ax.add_patch(rect)
                ax.text(x1, y1 - 4, f"GT: {class_names[int(cls)]}", color='lime', fontsize=10, weight='bold')

    # ========== Draw Predicted Boxes ==========
    pred_result = results[i]
    for box in pred_result.boxes:
        cls_id = int(box.cls[0])
        conf = float(box.conf[0])
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1,
                                 linewidth=2, edgecolor='red', facecolor='none')
        ax.add_patch(rect)
        ax.text(x1, y1 - 4, f"{conf:.2f}",
                color='red', fontsize=16, weight='bold')

plt.tight_layout()
plt.show()